new/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path

from task.views import index, TaskCreateView, TagCreateView, TaskUpdateView, TagUpdateView, TaskDeleteView, \
    TagDeleteView, TaskListView, TagListView, change_status

urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tasks/update/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("task/delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/change/<int:pk>/", change_status, name="task-change")
]


app_name = "task"

task/models.py
from django.db import models


class Tag(models.Model):
    tag = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.tag


class Task(models.Model):
    content = models.CharField(max_length=100)
    started_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tags")

    class Meta:
        ordering = ["done", "-started_at"]

task/forms.py
from django import forms
from task.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = ('content', "deadline", "tags",)

task/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from task.forms import TaskForm
from task.models import Task, Tag


def index(request):
    num_task = Task.objects.count()
    num_cars = Tag.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_task": num_task,
        "num_tag": num_cars,
        "num_visits": num_visits + 1,
    }
    return render(request, "task/index.html", context=context)


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "task/task_list.html"
    queryset = Task.objects.all()


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "task/tag_list.html"
    queryset = Tag.objects.all()


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "task/task_form.html"
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "task/task_form.html"
    success_url = reverse_lazy("task:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "task/task_confirm_delete.html"
    success_url = reverse_lazy("task:task-list")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "task/tag_form.html"
    success_url = "/"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "task/tag_confirm_delete.html"


def change_status(request, pk):
    task = Task.objects.get(pk=pk)
    if task.done:
        task.done = False
        task.save()
    else:
        task.done = True
        task.save()
    return HttpResponseRedirect(reverse_lazy("task:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
{% block body %}

  <body>
<header class="header">
  <div class="header_content">
    <h2><a href="/" class="link_color_white">Task manager</a></h2>
    <div>

    </div>

  </div>
</header>
<div class="container-fluid">
  <div class="row nomar-right">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="content_wrapper col-sm-10">
      <div class="content_detail">

        {% block content %}{% endblock %}


      </div>
    </div>

  </div>
</div>
</body>

</html>
{% endblock %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group sidebar">
  <li class="list-group-item sidebar-item"><a href="{% url 'task:index' %}" class="link_color">Home</a></li>
  <li class="list-group-item sidebar-item"><a href="{% url 'task:task-list' %}" class="link_color">Task</a></li>
  <li class="list-group-item sidebar-item"><a href="{% url 'task:tag-list' %}" class="link_color">Tags</a></li>
</ul>

templates/task/index.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h1>Welcome to ur Task manager </h1>
    <h2> You have:</h2>
    <ul>
        <li><strong>Task:</strong><a href="{% url "task:tag-list" %}"> {{ num_task }}</a></li>
        <li><strong>Tag:</strong><a href="{% url "task:tag-list" %}"> {{ num_tag }}</a></li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>
  </div>

{% endblock %}

templates/task/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div>
   <h1>Delete Task</h1>
<p>Are u sure u really wanna to delete this tag: {{ tag.tag }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
   <a href="/tags/" class="btn btn-primary" role="button">Cancel</a>
  </form>
  </div>

{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-success">
    {% if object %}
      <a href="{% url "task:tag-list" %}" class="btn btn-primary" role="button">Cancel</a>
    {% endif %}

  </form>
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <tr>

  <div class="car_list_features">
{#  bad practic for button in h1, but i not have time to fix it, sorry(#}
    <h1>Tag list <a href="{% url "task:tag-create" %}" class="btn btn-success">+</a></h1>
    {% if tag_list %}

      <table class="table table_style">
      <thead class="thead-dark">
      <tr>
        <th scope="col">id</th>
          <th scope="col">Tag</th>
        <th scope="col">update</th>
        <th scope="col">delete</th>



      </tr>
      </thead>
      <tbody>
      {% for tag in tag_list %}
        <tr>

          <td>{{ tag.id }}</td>
          <td>{{ tag.tag }}</td>
          <td><a href="{% url "task:tag-update" pk=tag.id %}" class="btn btn-success">Update</a></td>
          <td><a href="{% url "task:tag-delete" pk=tag.id%}" class="btn btn-danger">Delete</a></td>

        </tr>
      {% endfor %}

    {% else %}
      <p>No tags found</p>
    {% endif %}

    </tbody>
    </table>
</div>
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task</h1>
<p>Are u sure u really wanna to delete this task: {{ task.content }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
   <a href="/tasks/" class="btn btn-primary" role="button">Cancel</a>
  </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-success">
    <a href="{% url "task:task-list" %}" class="btn btn-danger">Cancel</a>

  </form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <tr>

  <div class="car_list_features">
  {#  bad practic for button in h1, but i not have time to fix it, sorry( #}
    <h1>Task list <a href="{% url "task:task-create"%}"class="btn btn-success">+</a></h1>

    {% if task_list %}

      <table class="table table_style">
      <thead class="thead-dark">
      <tr>
        <th scope="col">id</th>
          <th scope="col">Task discription</th>
          <th scope="col">Tags</th>
          <th scope="col">Started</th>
          <th scope="col">Deadline</th>
          <th scop="col">status</th>
          <th scop="col">Change status</th>
          <th scop="col">Update task</th>
          <th scop="col">Delete task</th>


      </tr>
      </thead>
      <tbody>
      {% for task in task_list %}
        <tr>

          <td>{{ task.id }}</td>
          <td>{{ task.content }}</td>
          <td>{% for tag in task.tags.all %}
                {{ tag }}
            {% empty %}
            <p>No tags(</p>
          {% endfor %}
          </td>
          <td>{{ task.started_at }}</td>
          <td>{{ task.deadline }}</td>
            {% if task.done %}
          <td>Complete!</td>
              {% else %}
              <td>In proces..</td>
          {% endif %}
          <td><a href="{% url "task:task-change" pk=task.pk %}" class="btn btn-dark">Change</a></td>
          <td><a href="{% url "task:task-update" pk=task.pk %}" class="btn btn-primary">Update</a></td>
          <td><a href="{% url "task:task-delete" pk=task.pk %}" class="btn btn-danger">Delete</a></td>
        </tr>
      {% endfor %}

    {% else %}
      <p>No task found</p>
    {% endif %}

    </tbody>
    </table>
</div>
{% endblock %}